
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const Admin = lazy(() => import("./pages/Admin.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const CommissionsPage = lazy(() => import("./pages/CommissionsPage.tsx"));
const ContratApporteur = lazy(() => import("./pages/ContratApporteur.tsx"));
const ContratApporteurPage = lazy(() => import("./pages/ContratApporteurPage.tsx"));
const DashboardPage = lazy(() => import("./pages/DashboardPage.tsx"));
const GuideParrainage = lazy(() => import("./pages/GuideParrainage.tsx"));
const LeadForm = lazy(() => import("./pages/LeadForm.tsx"));
const LeadsPage = lazy(() => import("./pages/LeadsPage.tsx"));
const OnboardingPage = lazy(() => import("./pages/OnboardingPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/admin", element: <UserGuard><Admin /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/commissions-page", element: <UserGuard><CommissionsPage /></UserGuard>},
	{ path: "/commissionspage", element: <UserGuard><CommissionsPage /></UserGuard>},
	{ path: "/contrat-apporteur", element: <UserGuard><ContratApporteur /></UserGuard>},
	{ path: "/contratapporteur", element: <UserGuard><ContratApporteur /></UserGuard>},
	{ path: "/contrat-apporteur-page", element: <UserGuard><ContratApporteurPage /></UserGuard>},
	{ path: "/contratapporteurpage", element: <UserGuard><ContratApporteurPage /></UserGuard>},
	{ path: "/dashboard-page", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/dashboardpage", element: <UserGuard><DashboardPage /></UserGuard>},
	{ path: "/guide-parrainage", element: <UserGuard><GuideParrainage /></UserGuard>},
	{ path: "/guideparrainage", element: <UserGuard><GuideParrainage /></UserGuard>},
	{ path: "/lead-form", element: <UserGuard><LeadForm /></UserGuard>},
	{ path: "/leadform", element: <UserGuard><LeadForm /></UserGuard>},
	{ path: "/leads-page", element: <UserGuard><LeadsPage /></UserGuard>},
	{ path: "/leadspage", element: <UserGuard><LeadsPage /></UserGuard>},
	{ path: "/onboarding-page", element: <UserGuard><OnboardingPage /></UserGuard>},
	{ path: "/onboardingpage", element: <UserGuard><OnboardingPage /></UserGuard>},

];
